# .pre-commit-config.yaml
# repos for pre-commit, and linting via black and flake 8

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: main
  hooks:
    - id: check-added-large-files
    - id: detect-aws-credentials
    - id: detect-private-key

- repo: https://github.com/psf/black
  rev: main
  hooks:
    - id: black

- repo: https://github.com/PyCQA/flake8
  rev: main
  hooks:
    - id: flake8


